---
DefaultContentLanguage: en
MetaDataFormat: yaml
Paginate: 300
baseURL: "https://www.thenewdynamic.org"
enableRobotsTXT: true
googleAnalytics: ""
languageCode: en-us
config: config.yaml
theme: "hugo-base-layouts"
title: Hugo Starter Demo
#themesDir: "src/themes"
#layoutDir: "src/layouts"
mediaTypes:
  text/netlify:
    delimiter: ""
    suffix: ""
menu:
  main:
    -
      identifier: home
      name: "Home"
      url: /
      weight: 1
    -
      identifier: news
      name: "News"
      url: /posts/
      weight: 20
    -
      identifier: about
      name: About
      url: /about/
      weight: 60
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - REDIR
params:
  description: "Build Faster Better Websites with modern tools and techniques"
  logo: ""
  dev:
    fonts_path: "static/dist/Fonts"
    css_path: "static/dist/css"
    js_path: "static/dist/js"


preserveTaxonomyNames: true
related:
  includeNewer: true
  indices:
    -
      name: tool
      toLower: true
      weight: 100
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
social:
  facebook:
  twitter:
  instagram:
taxonomies:
  series: series
  tag: tags
  tools: tools
